---
- name: Add AWS EKS Helm repository
  command: helm repo add eks https://aws.github.io/eks-charts
  changed_when: False

- name: Update Helm repositories
  command: helm repo update
  changed_when: False

- name: Install AWS Load Balancer Controller
  command: >-
    helm install aws-load-balancer-controller eks/aws-load-balancer-controller
    --namespace kube-system
    --set clusterName={{ kubectl_context_name }}
    --set serviceAccount.create=false
    --set serviceAccount.name=aws-load-balancer-controller
  register: alb_controller_result
  failed_when: "alb_controller_result.rc != 0 and 'cannot re-use a name that is still in use' not in alb_controller_result.stderr"
  changed_when: "'has been installed' in alb_controller_result.stdout or 'has been upgraded' in alb_controller_result.stdout"

- name: Add Ingress NGINX Helm repository
  command: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
  changed_when: False

- name: Install Ingress NGINX Controller
  command: >-
    helm install ingress-nginx ingress-nginx/ingress-nginx
    --namespace ingress-nginx
    --create-namespace
  register: nginx_ingress_result
  failed_when: "nginx_ingress_result.rc != 0 and 'cannot re-use a name that is still in use' not in nginx_ingress_result.stderr"
  changed_when: "'has been installed' in nginx_ingress_result.stdout or 'has been upgraded' in nginx_ingress_result.stdout"
