variable "environment" {}
variable "vpc_id" {}
variable "private_subnet_ids" {}
variable "cluster_name" {}
variable "node_group_name" {}
variable "instance_types" {}
variable "desired_size" {}
variable "min_size" {}
variable "max_size" {}
variable "authentication_mode" {}
